version: "2"

run:
  timeout: 5m

linters:
  default: all
  disable:
    - exhaustruct
    - wrapcheck
    - depguard
    - noinlineerr
    - perfsprint
    - wsl
    - err113
    - paralleltest
    - testpackage
    - testifylint
    - revive
